In [3]:
%matplotlib
import numpy as np
import cv2
from tensorflow.keras.applications import mobilenet_v2
from time import sleep

# Set up neural network
model = mobilenet_v2.MobileNetV2(weights='imagenet')

# Set up video capture
cap = cv2.VideoCapture(0)

# Score list
score_list = []

# Function to call for each frame
def update(i):
    # Capture frame from webcam
    ret, frame_bgr = cap.read()
    print("Frame_bgr:", frame_bgr)
    assert ret
    frame = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)    
    print("Frame:",frame)
    min_dim = np.min(frame.shape[0:2])
    frame = cv2.resize(frame[0:min_dim, 0:min_dim, :], (224, 224))

    # Update classification
    processed_image = mobilenet_v2.preprocess_input(np.expand_dims(frame, axis=0))
    predictions = model.predict(processed_image)
    label = mobilenet_v2.decode_predictions(predictions)
    
    for name, desc, score in mobilenet_v2.decode_predictions(predictions)[0]:
        if desc == "water_bottle": 
            score_list.append(100 * score)
            #print('({:.2f}%)'.format(100 * score))
            break
    
    return

def calculate_std(score_list, mean):
    sum_of_deviations = 0.0
    for s in score_list:
        sum_of_deviations += (s - mean)**2
    
    std = (sum_of_deviations/len(score_list))**0.5
    return std

for j in range(10):
    update(j)
    sleep(0.1)
    
cv2.destroyAllWindows()
cap.release()

mean = sum(score_list)/len(score_list)
std = calculate_std(score_list, mean)

print('Mean: {:.2f}%'.format(mean))
print('Standard Deviation: {:.2f}%'.format(std))
print(score_list)

Using matplotlib backend: Qt5Agg
Frame_bgr: [[[60 75 79]
  [62 76 80]
  [64 77 84]
  ...
  [ 7 18 32]
  [ 8 17 29]
  [ 9 18 31]]

 [[59 74 78]
  [60 75 79]
  [62 75 82]
  ...
  [ 8 16 31]
  [ 8 17 29]
  [ 8 17 29]]

 [[59 73 80]
  [60 74 81]
  [60 74 81]
  ...
  [ 8 16 31]
  [ 8 17 29]
  [ 8 17 29]]

 ...

 [[52 41 40]
  [55 44 44]
  [53 45 42]
  ...
  [48 62 55]
  [48 57 56]
  [47 56 55]]

 [[53 41 43]
  [55 43 45]
  [55 45 42]
  ...
  [49 60 54]
  [47 59 57]
  [46 58 56]]

 [[57 45 47]
  [58 46 48]
  [58 47 46]
  ...
  [47 61 54]
  [48 60 58]
  [47 59 57]]]
Frame: [[[79 75 60]
  [80 76 62]
  [84 77 64]
  ...
  [32 18  7]
  [29 17  8]
  [31 18  9]]

 [[78 74 59]
  [79 75 60]
  [82 75 62]
  ...
  [31 16  8]
  [29 17  8]
  [29 17  8]]

 [[80 73 59]
  [81 74 60]
  [81 74 60]
  ...
  [31 16  8]
  [29 17  8]
  [29 17  8]]

 ...

 [[40 41 52]
  [44 44 55]
  [42 45 53]
  ...
  [55 62 48]
  [56 57 48]
  [55 56 47]]

 [[43 41 53]
  [45 43 55]
  [42 45 55]
  ...
  [54 60 49]
  [57 59 47]
  [56 

ZeroDivisionError: division by zero